### ISSUE TITLE
Installation error (get_git_version() can't determine current PyRK version)

### ISSUE THREAD

**Issue by andrewryh** [pyrk/pyrk#40]
`python setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import pyrk
  File "/home/andrei2/Desktop/git/pyrk/pyrk/__init__.py", line 6, in <module>
    from version import get_git_version
ModuleNotFoundError: No module named 'version'
`

**Comment by katyhuff** [comment]
Closed with #41 .
