### ISSUE TITLE
get_git_version: raise ValueError("Cannot find the version number!") Fix 

### ISSUE THREAD

**Issue by SterlingButters** [pyrk/pyrk#63]
Using PyRK version (0.1.dev44a238e) I received the following error during installation using setup.py; I modified ver.py to get through the installation via the attached file that you can use to replace ver.py (change file extension .txt to .py). 
[ver.txt](https://github.com/pyrk/pyrk/files/1523558/ver.txt)

**Comment by SterlingButters** [comment]
I take it back... you can complete the installation with the above but example files do not have access to modules that should be installed... something is wrong

**Comment by gbremer** [comment]
How are you trying to run the examples, and what is the error? As background, did you install Anaconda and install the requirements for pyrk? I can take a deeper look at this tomorrow.

**Comment by SterlingButters** [comment]
I have Anaconda3 installed and requirements. I am using PyCharm IDE. PyRK library and modules should be installed to site-packages, no? I can verify via "pip list" that PyRK is present using my mentioned installation method. However opening and running "input.py" does not access modules such as "Utilities". Using cloned PyRK setup.py file for installation yields the ValueError.

**Comment by gbremer** [comment]
Thank you for that. Can you post the stack trace you are getting?

**Comment by SterlingButters** [comment]
Whoa, I dont know what happened but it just worked when trying to replicate the issue, only thing I did different was clone through Github Desktop instead of downloading as zip, now to see if examples work

**Comment by SterlingButters** [comment]
It seems that downloading the zip provides a different version (0.1.dev44a238e) than Github Desktop (0.2.dev70a9266) or I am missing something completely

**Comment by SterlingButters** [comment]
Yup, examples work as well

**Comment by SterlingButters** [comment]
Not sure what did the trick tbh

**Comment by SterlingButters** [comment]
Examples do not work. Pyrk is found via "pip list" yet I cannot find in site-packages. Modules of pyrk are not found via import i.e. "utilities.ur", "materials.flibe", etc are unresolved references

**Comment by augusto-vib** [comment]
Hello! 

I am trying to run the code but it keeps crashing. I managed to installed it only by cloning it from git. If I downloaded the zip file, it didn't even recognized the version. I have anaconda 3 and the examples are crashing... if you an idea  what is going on, a comment would be highly appreciated it

**Comment by SterlingButters** [comment]
Can you find what version is installed?

**Comment by SterlingButters** [comment]
Hmm what do you mean by crashing? You mean you get an error?

**Comment by gbremer** [comment]
Following along.... @augusto-vib, can you provide a snapshot of your terminal session, showing the commands you ran to install pyrk, run the examples, and then showing the errors you received?

**Comment by augusto-vib** [comment]
Hello Grant!

I have anaconda3...when I install it, the first "fishy" message appears at the very beginning of the installation:

augusto@augusto-Lenovo-G510:~/Downloads/pyrk$ python setup.py install
/home/augusto/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:360: UserWarning: The version specified ('0.2.dev70a9266') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

I just cloned PYRK with git. Now, it appears this message but it actually installs. But when for instance,  I try to run one of the examples (~pyrk/examples/default/input.py) by typing:( python ../../pyrk/driver.py --infile=input.py ), it gives an error message as follows:

augusto@augusto-Lenovo-G510:~/Downloads/pyrk/examples/default$ python ../../pyrk/driver.py --infile=input.py
Traceback (most recent call last):
  File "../../pyrk/driver.py", line 281, in <module>
    main(args, curr_dir)
  File "../../pyrk/driver.py", line 238, in main
    infile = load_infile(args.infile)
  File "../../pyrk/driver.py", line 231, in load_infile
    infile = importlib.import_module(file_name)
  File "/home/augusto/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/augusto/Downloads/pyrk/examples/default/input.py", line 110, in <module>
    ti = Timer(t0=t0, tf=tf, dt=dt)
  File "/home/augusto/Downloads/pyrk/pyrk/timer.py", line 25, in __init__
    self.t0 = validation.validate_ge("t0", t0, 0.0 * units.seconds)
  File "/home/augusto/anaconda3/lib/python3.6/site-packages/pyrk-0.2.dev70a9266-py3.6.egg/pyrk/inp/validation.py", line 19, in validate_ge
    if validate_num(valname, val) < llim:
  File "/home/augusto/anaconda3/lib/python3.6/site-packages/pint/quantity.py", line 924, in <lambda>
    __lt__ = lambda self, other: self.compare(other, op=operator.lt)
  File "/home/augusto/anaconda3/lib/python3.6/site-packages/pint/quantity.py", line 914, in compare
    raise ValueError('Cannot compare Quantity and {0}'.format(type(other)))
ValueError: Cannot compare Quantity and <class 'pint.unit.build_quantity_class.<locals>.Quantity'>

Hope you can help!

**Comment by augusto-vib** [comment]
Hello! 

I was wondering if you had a chance to see why the current version of the code while installed using anaconda3, still crashes when I try to make some runs (see my comment from above from December 13th). Would be great if you could check that the current version that is cloned with git is working properly. Thanks !

**Comment by gbremer** [comment]
Augusto —

I will dust this off and clear this task off shortly. Sorry for the delay here.

**Comment by Luster354** [comment]
Hi I am quite new to python as well as github so im not sure if I have done this set up proccess properly. I downloaded the posted zip file and extracted its content. I opened the folder in my  Anaconda3 command window and the the python setup script.
 
C:\Users\Yugi\Documents\Senior Design 2\Python\pyrk-master\pyrk-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    version=get_git_version(),
  File "C:\Users\Yugi\Documents\Senior Design 2\Python\pyrk-master\pyrk-master\pyrk\ver.py", line 90, in get_git_version
    raise ValueError("Cannot find the version number!")
ValueError: Cannot find the version number!

And I am not sure what it means by it cannot find the version number. I read the previous contents of this page and I'm still a little confused but do I have the wrong version of Python installed?

**Comment by katyhuff** [comment]
Closed with #94 .
