### ISSUE TITLE
ValueError: Cannot compare Quantity and <class 'float'>

### ISSUE THREAD

**Issue by scaysbri** [pyrk/pyrk#72]
I'm getting a "ValueError: Cannot compare Quantity and <class 'float'>" when I run the newly installed pyrk code. This seems to be a pint error but debugging both tf and t_feedback appear to be in the correct units so I'm a bit stumped.

pint and pyrk both reported as correctly installed.

I have tried running in Python3.7 and Python2.7 on both 64 bit and 32 Windows installations of Anaconda. I have the same error on a standalone installation and a web connected laptop.

In order to install the code I had to move the RELEASE-VERSION file into the same directory as setup.py but other than that I have installed as is from github. Latest version is reported as 0.1.dev44a238e from the RELEASE-VERSION file.

Input file is the one in examples/sfr input.py but others give the same error.

Error dump...

(base) C:\Users\iansc\Anaconda3\Lib\site-packages\pyrk-0.1.dev44a238e-py3.7.egg\pyrk>python driver.py
Traceback (most recent call last):
  File "driver.py", line 281, in <module>
    main(args, curr_dir)
  File "driver.py", line 238, in main
    infile = load_infile(args.infile)
  File "driver.py", line 231, in load_infile
    infile = importlib.import_module(file_name)
  File "C:\Users\iansc\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\iansc\Anaconda3\Lib\site-packages\pyrk-0.1.dev44a238e-py3.7.egg\pyrk\input.py", line 100, in <module>
    ti = Timer(t0=t0, tf=tf, dt=dt)
  File "C:\Users\iansc\Anaconda3\Lib\site-packages\pyrk-0.1.dev44a238e-py3.7.egg\pyrk\timer.py", line 27, in __init__
    self.tf = validation.validate_ge("tf", tf, t_feedback)
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pyrk-0.2-py3.7.egg\pyrk\inp\validation.py", line 19, in validate_ge
    if validate_num(valname, val) < llim:
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pint-0.10.dev0-py3.7.egg\pint\quantity.py", line 1265, in <lambda>
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pint-0.10.dev0-py3.7.egg\pint\quantity.py", line 76, in wrapped
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pint-0.10.dev0-py3.7.egg\pint\quantity.py", line 1246, in compare
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pint-0.10.dev0-py3.7.egg\pint\quantity.py", line 1268, in <lambda>
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pint-0.10.dev0-py3.7.egg\pint\quantity.py", line 76, in wrapped
  File "C:\Users\iansc\AppData\Roaming\Python\Python37\site-packages\pint-0.10.dev0-py3.7.egg\pint\quantity.py", line 1255, in compare
ValueError: Cannot compare Quantity and <class 'float'>

**Comment by scaysbri** [comment]
SOLVED - Example input.py files have:
```
from utilities.ur import units
import th_component as th
from timer import Timer
from materials.sfrmetal import SFRMetal
from materials.sodium import Sodium
```
whereas they should have:
```
from pyrk.utilities.ur import units
import pyrk.th_component as th
from pyrk.timer import Timer
from pyrk.materials.sfrmetal import SFRMetal
from pyrk.materials.sodium import Sodium
```
This solves the problem
