### ISSUE TITLE
error when run module pyrk 

### ISSUE THREAD

**Issue by ayinurazizah844** [pyrk/pyrk#73]
how to solve errors "package directory 'pyrk\utils' does not exist" when i run the pyrk module there is an error like that after writing "writing manifest file 'pyrk.egg-info\SOURCES.txt' ".?
i run python in miniconda and i use windows.

**Comment by katyhuff** [comment]
There is not enough information to debug your issue. But the following are true:
- We don't explicitly support windows or run tests on windows. 
- I suspect you have not installed pyrk. You must run setup.py to install pyrk. 

To get more help, please give us more information:

- What command did you run, exactly, to "run the pyrk module"?
- What error, exactly, do you see? Copy the *entire error* as well as the commands that you executed in order to see that error.

**Comment by ayinurazizah844** [comment]
I have finished installing the pyrk module until the "nostests pyrk" command and the results are ok,
then I run the input in the example everything works but no results folder "pyrk.h5",
then I run driver.py which is in the pyrk module and there is an error
"Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pyrk-0.2.dev7031ad0-py2.7.egg\pyrk\driver.py", line 281, in <module>
    main(args, curr_dir)
  File "C:\Python27\Lib\site-packages\pyrk-0.2.dev7031ad0-py2.7.egg\pyrk\driver.py", line 238, in main
    infile = load_infile(args.infile)
  File "C:\Python27\Lib\site-packages\pyrk-0.2.dev7031ad0-py2.7.egg\pyrk\driver.py", line 231, in load_infile
    infile = importlib.import_module(file_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named input"

**Comment by vigneshwar-manickam** [comment]
I started off with a similar problem.

I used the following command:
python driver.py --infile=input.py --plotdir=out

Received the following errors:
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "driver.py", line 281, in <module>
    main(args, curr_dir)
  File "driver.py", line 256, in main
    db=out_db)
  File "/Users/vignesh.manickam/opt/anaconda3/envs/pyrk-27-test-environment/lib/python2.7/site-packages/pyrk-0.2.deve88471b-py2.7.egg/pyrk/inp/sim_info.py", line 79, in __init__
    self.register_recorders()
  File "/Users/vignesh.manickam/opt/anaconda3/envs/pyrk-27-test-environment/lib/python2.7/site-packages/pyrk-0.2.deve88471b-py2.7.egg/pyrk/inp/sim_info.py", line 85, in register_recorders
    timeseries=False)
  File "/Users/vignesh.manickam/opt/anaconda3/envs/pyrk-27-test-environment/lib/python2.7/site-packages/pyrk-0.2.deve88471b-py2.7.egg/pyrk/db/database.py", line 253, in register_recorder
    self.add_row(tab, recorder())
  File "/Users/vignesh.manickam/opt/anaconda3/envs/pyrk-27-test-environment/lib/python2.7/site-packages/pyrk-0.2.deve88471b-py2.7.egg/pyrk/inp/sim_info.py", line 191, in metadata
    'revision': self.get_git_revision_short_hash(),
  File "/Users/vignesh.manickam/opt/anaconda3/envs/pyrk-27-test-environment/lib/python2.7/site-packages/pyrk-0.2.deve88471b-py2.7.egg/pyrk/inp/sim_info.py", line 158, in get_git_revision_short_hash
    return subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'])
  File "/Users/vignesh.manickam/opt/anaconda3/envs/pyrk-27-test-environment/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128
Closing remaining open files:pyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...done

**Comment by vigneshwar-manickam** [comment]
issue solved. I was able to just use git clone and run the simulation just fine.

**Comment by katyhuff** [comment]
Thanks @vigneshwar-manickam
