### ISSUE TITLE
Validation.py does not properly compare two pint Quantity objects

### ISSUE THREAD

**Issue by samgdotson** [pyrk/pyrk#76]
I am attempting to run the examples in ``pyrk`` and cannot successfully run any of them.

Steps taken until error:

```shell
git clone git@github.com:pyrk/pyrk.git
python setup.py install
pip install -r requirements.txt
mkdir outfiles
python pyrk/driver.py --infile=examples/default/input.py --plotdir=outfiles
```
~~In the future I will fork ``pyrk`` and then clone~~
Edit: cloned a fork, followed the same steps, received same traceback.

The full Traceback

```shell
Traceback (most recent call last):
  File "pyrk/driver.py", line 281, in <module>
    main(args, curr_dir)
  File "pyrk/driver.py", line 238, in main
    infile = load_infile(args.infile)
  File "pyrk/driver.py", line 231, in load_infile
    infile = importlib.import_module(file_name)
  File "/home/dotson/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "examples/default/input.py", line 110, in <module>
    ti = Timer(t0=t0, tf=tf, dt=dt)
  File "/home/dotson/research/pyrk/pyrk/timer.py", line 27, in __init__
    self.tf = validation.validate_ge("tf", tf, t_feedback)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/inp/validation.py", line 19, in validate_ge
    if validate_num(valname, val) < llim:
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pint/quantity.py", line 1609, in <lambda>
    __lt__ = lambda self, other: self.compare(other, op=operator.lt)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pint/quantity.py", line 1590, in compare
    return op(self._magnitude, other)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pint/quantity.py", line 1612, in <lambda>
    __gt__ = lambda self, other: self.compare(other, op=operator.gt)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pint/quantity.py", line 1599, in compare
    raise ValueError("Cannot compare Quantity and {}".format(type(other)))
ValueError: Cannot compare Quantity and <class 'float'>
```

It leads to ``validation.py`` (but, strangely, not the file in the input directory, but somewhere else in the anaconda system). 

I have tried the following:
1. Verifying the types of ``validation_num(valname, val)`` and ``llim`` (they are both pint objects). 
2. Inserting the following line
```python
"""
if type(validate_num(valname, val) is type(llim):
    if validate_num(valname, val) < llim:
        msg = valname + " must be greater than or equal to "
```
This successfully passed the comparison problem, but lead to a different Traceback:
```shell
  File "pyrk/driver.py", line 17, in <module>
    from pyrk.inp import sim_info
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/inp/sim_info.py", line 5, in <module>
    from pyrk import neutronics
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/neutronics.py", line 11, in <module>
    class Neutronics(object):
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/neutronics.py", line 19, in Neutronics
    timer=Timer(),
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/timer.py", line 31, in __init__
    num=self.timesteps()),
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/timer.py", line 70, in timesteps
    return self.t_idx(self.tf) + 1
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/timer.py", line 43, in t_idx
    return self.idx_from_t(time=time, t0=self.t0, dt=self.dt)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.deve88471b-py3.7.egg/pyrk/timer.py", line 56, in idx_from_t
    num = float(time.magnitude) - float(t0.magnitude)
AttributeError: 'NoneType' object has no attribute 'magnitude'
```

I'm not sure if the problem is in my installation steps or if I missed a requirement. The issue with missing requirements in #58 doesn't seem to be the cause.

**Comment by katyhuff** [comment]
Just to summarize, I think it might be an issue inside pint, possibly related to changes in python 3.7.

**Comment by samgdotson** [comment]
I'm still not sure what the issue is, but now I'm skeptical about the problem being caused by python3.7. 

I just tried 
```shell
conda create -n envtest python=3.6 anaconda
source activate envtest
cd pyrk
python setup.py install
pip install -r requirements.txt
python pyrk/driver.py --infile=examples/default/input.py --plotdir=outfiles/
```
and got an identical traceback as before, but with the env and python version changed. 
Full new traceback
```shell
Traceback (most recent call last):
  File "pyrk/driver.py", line 281, in <module>
    main(args, curr_dir)
  File "pyrk/driver.py", line 238, in main
    infile = load_infile(args.infile)
  File "pyrk/driver.py", line 231, in load_infile
    infile = importlib.import_module(file_name)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "examples/default/input.py", line 110, in <module>
    ti = Timer(t0=t0, tf=tf, dt=dt)
  File "/home/dotson/research/pyrk/pyrk/timer.py", line 27, in __init__
    self.tf = validation.validate_ge("tf", tf, t_feedback)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pyrk-0.2.dev7031ad0-py3.6.egg/pyrk/inp/validation.py", line 19, in validate_ge
    if validate_num(valname, val) < llim:
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pint/quantity.py", line 1609, in <lambda>
    __lt__ = lambda self, other: self.compare(other, op=operator.lt)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pint/quantity.py", line 1590, in compare
    return op(self._magnitude, other)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pint/quantity.py", line 1612, in <lambda>
    __gt__ = lambda self, other: self.compare(other, op=operator.gt)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "/home/dotson/anaconda3/envs/pint_test/lib/python3.6/site-packages/pint/quantity.py", line 1599, in compare
    raise ValueError("Cannot compare Quantity and {}".format(type(other)))
ValueError: Cannot compare Quantity and <class 'float'>
```

**Comment by samgdotson** [comment]
I realized that if I want changes in ``validaiton.py`` to take hold, I need to execute ``python setup.py install`` each time. 
Updates: 
I tried running ``pdb`` and stepping through ``validation.py``. 
1. ``validate_ge`` runs successfully several times before stopping at the following line 

```shell
=============================================
valname is t0
type of llim is <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
type of checknum is <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
=============================================
val is 0.0 second
llim is 0.0 second
> /home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev7031ad0-py3.7.egg/pyrk/inp/validation.py(29)validate_ge()
-> if type(val) == type(llim):
(Pdb) l
 24  	
 25  	    check_number = validate_num(valname, val)
 26  	    print(f"val is {val}")
 27  	    print(f"llim is {llim}")
 28  	    breakpoint()
 29  ->	    if type(val) == type(llim):
 30  	
 31  	        if validate_num(valname, val) < llim:
 32  	
 33  	            msg = valname + " must be greater than or equal to "
 34  	            msg += str(llim) + ".\n"
```

2. I tried recreating the error in ipython and cannot. However, it doesn't look like a bug in Pint.
 
```python
In [1]: from pint import UnitRegistry                                           

In [2]: units = UnitRegistry()                                                  

In [3]: t0 = 0.0*units.seconds                                                  

In [4]: tf = 0.0*units.seconds                                                  

In [5]: if type(t0) is type(tf): 
   ...:     if t0 < tf: 
   ...:         print("t0 is less than tf") 
   ...:     else: 
   ...:         print("the types are the same") 
   ...:         print(t0, type(t0)) 
   ...:         print(tf, type(tf)) 
   ...:                                                                         
the types are the same
0.0 second <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>
0.0 second <class 'pint.quantity.build_quantity_class.<locals>.Quantity'>

In [6]: type(t0) == type(tf)                                                    
Out[6]: True
```

**Comment by samgdotson** [comment]
Okay, I've tried a few different versions of the old code and [this version](https://github.com/pyrk/pyrk/commit/510e1b7f4f75802420aeba255b9e0e769ffa4052) seems like the last "stable" version that has successful examples.

**Comment by katyhuff** [comment]
You seem to be installing the dependencies after installing pyrk. This isn't quite right. The opposite is appropriate. I'm sure that since you've now done it many times, the dependencies are installed, so `pip install -r requirements.txt` is no longer doing anything, but it's something to consider. . .
