### ISSUE TITLE
Allow driver.py to generate plots when --plotdir flag is given

### ISSUE THREAD

**Issue by samgdotson** [pyrk/pyrk#78]
Current behavior: The ``--plotdir`` flag is ignored by PyRK and no plots are generated. Without ``--plotdir``, no plots are generated. Desired behavior: If a user specifies an output directory for plots, PyRK should try to generate plots. 

There may be some conflict with the ``pbfhr`` example, which used Bokeh to make interactive plots in a Jupyter notebook.
This indicates that there might be some cases that mean PyRK can't produce plots.

**Comment by samgdotson** [comment]
Update: 
1. Plotting was removed in 2015 with PR #25 (specifically this [commit](https://github.com/pyrk/pyrk/commit/be0dc509a611d9ce0f4a7b2552c3ad1571fee473))
2. In ``driver.py`` calling ``solve()`` is stored as a dummy variable ``_``. This should be changed to an actual variable name.
3. Adding the plotter function does not work because there have been changes to the ``neutronics.py`` class structure. Presumably, this is true for all plots, not just reactivity.

Here is the error message
```bash
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
Traceback (most recent call last):
  File "../pyrk/pyrk/driver.py", line 283, in <module>
    args = ap.parse_args()
  File "../pyrk/pyrk/driver.py", line 264, in main
    print(plotdir)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/utilities/plotter.py", line 31, in plot
    plot_temps_together(x, y, si)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/utilities/plotter.py", line 71, in plot_temps_together
    idx = 1 + si.ne._npg + si.ne._nref + si.ne._ndg + num
AttributeError: 'Neutronics' object has no attribute '_nref'
```
5. I'm not sure what ``PostScript`` is at this time.
6. There should be an additional issue to resolve the expected attributes in ``plotter.py``.
