### ISSUE TITLE
[bug/question]

### ISSUE THREAD

**Issue by samgdotson** [pyrk/pyrk#82]
Currently, running ``driver.py`` as a script does not work if the current directory is not a git repository. 

Running it from my directory ``~/research/``, where I have cloned the ``pyrk`` repo, yields:

```bash
$ python pyrk/pyrk/driver.py --infile=min_ss.py --plotdir=./
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "pyrk/pyrk/driver.py", line 281, in <module>
    main(args, curr_dir)
  File "pyrk/pyrk/driver.py", line 256, in main
    db=out_db)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/inp/sim_info.py", line 79, in __init__
    self.register_recorders()
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/inp/sim_info.py", line 85, in register_recorders
    timeseries=False)
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/db/database.py", line 253, in register_recorder
    self.add_row(tab, recorder())
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/inp/sim_info.py", line 191, in metadata
    'revision': self.get_git_revision_short_hash(),
  File "/home/dotson/anaconda3/lib/python3.7/site-packages/pyrk-0.2.dev51028e0-py3.7.egg/pyrk/inp/sim_info.py", line 158, in get_git_revision_short_hash
    return subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'])
  File "/home/dotson/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/dotson/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
Closing remaining open files:pyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...donepyrk.h5...done
```
This issue can be closed when one of the following have been done:
- [ ] An explanation for this behavior (it's possible this behavior is desirable and should be explained in the docs), or,
- [ ] the ``driver.py`` script is updated to run with a relative path from anywhere (the [tutorial](http://pyrk.github.io/tutorial.html) suggests this should be the case). 

@katyhuff do you know why this choice was made?

**Comment by samgdotson** [comment]
Update: The purpose for keeping track of the git version is for reproducibility. Running simulations with ``driver.py`` is not the optimal way to use ``pyrk`` for other applications.

**Comment by katyhuff** [comment]
The problem you're running into here is that you're trying to run pyrk without installing it. The tutorial begins with installation for this reason. If pyrk is installed, the git repo hash is stored in that moment in the build files. If it isn't installed, then you need to be running from within the directory (but that's for developers, not for users).
